Add missing dep to payment service
Fixes this problem when building payment service:

```
Error: Cannot find module '@openfeature/core'
Require stack:
- /usr/src/app/node_modules/@openfeature/server-sdk/dist/cjs/index.js
- /usr/src/app/charge.js
- /usr/src/app/index.js
```

Reproduce with:
```
docker compose build payment && docker compose up payment
```