Add missing dep to payment service (#198)
* Add missing dep to payment service

Fixes this problem when building payment service:

```
Error: Cannot find module '@openfeature/core'
Require stack:
- /usr/src/app/node_modules/@openfeature/server-sdk/dist/cjs/index.js
- /usr/src/app/charge.js
- /usr/src/app/index.js
```

Reproduce with:
```
docker compose build payment && docker compose up payment
```

* Revert "Add missing dep to payment service"

This reverts commit f93fa4eb333090cccb43fac60a21adac5bef4b5c.

* Bump package-lock using node 22

npm install
docker compose build payment && docker compose up payment

* Sync package.json and package-lock.json with upstream